/*
 * This source file was generated by the Gradle 'init' task
 */
package de.esempe.workflow;

import java.util.List;

import org.bson.Document;
import org.tinylog.Logger;

import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;

import de.esempe.workflow.Transition.TransistionType;
import dev.morphia.Datastore;
import dev.morphia.Morphia;
import dev.morphia.config.MorphiaConfig;
import dev.morphia.query.Query;
import jakarta.json.Json;
import jakarta.json.JsonObject;

public class App
{

	public static void main(final String[] args) throws InterruptedException
	{
		CDI.CONTAINER.isRunning();

		final App app = new App();
		// app.runDemoWorkflow();
		// app.runDemoMongoDB();
		app.runDemoMorphia();

	}

	private void runDemoMorphia()
	{
		final String uri = "mongodb://127.0.0.1:27017";
		final MongoClient mongoClient = MongoClients.create(uri);
		final MorphiaConfig config = MorphiaConfig.load();
		final Datastore datastore = Morphia.createDatastore(mongoClient, config);

		// final User user1 = new User("etienne");
		// final User save = datastore.save(user1);

		final Query<User> query = datastore.find(User.class);
		final List<User> users = query.iterator().toList();

		Logger.info("done");
	}

	private void runDemoMongoDB()
	{
		final String uri = "mongodb://127.0.0.1:27017";
		final MongoClient mongoClient = MongoClients.create(uri);
		final MongoDatabase database = mongoClient.getDatabase("testdb");

		database.createCollection("workflows");
		final MongoCollection<Document> collection = database.getCollection("workflows");

		// collection.insertOne(new Document().append("_id", new ObjectId()).append("title", "Workflow Admin-Rechte"));
		// collection.insertOne(new Document().append("_id", new ObjectId()).append("title", "Workflow WWS-Rechte"));

		final long countDocuments = collection.countDocuments();
		System.out.println("Anzahl: " + countDocuments);

		final Document firstDoc = collection.find().first();

		Logger.info("done");
	}

	private void runDemoWorkflow() throws InterruptedException
	{
		final Workflow wf = this.defineWorkflow();
		final Workflowinstance instance = new Workflowinstance(wf);

		final JsonObject data = Json.createObjectBuilder() //
				.add("pc", "R9575") //
				.add("dauer", 60) //
				.add("begründung", "SW-Installation").build();

		instance.start(data);
		Thread.sleep(5000);

		final List<Transition> currentTransistions = instance.getCurrentTransistions();
		instance.fireTransition(currentTransistions.get(0));

		Logger.info("done");
	}

	private Workflow defineWorkflow()
	{
		final Workflow result = CDI.CONTAINER.getType(Workflow.class);

		final State start = new State("Start");
		final State genehmigt = new State("Genehmigt");
		final State abgelehnt = new State("Abgelehnt");
		final State pruefen = new State("prüfen");

		final Transition automatischeGenehmigung = new Transition("Automatische Genehmigung", start, genehmigt);
		automatischeGenehmigung.setType(TransistionType.SYSTEM);

		var script = """
				import groovy.json.JsonSlurper
				def jsonSlurper = new JsonSlurper()
				def map = jsonSlurper.parseText(data)
				map.dauer == 4;
				""";

		final Rule ruleMinDauer = RuleCreator.build("Minimale Dauer", script);
		automatischeGenehmigung.setRule(ruleMinDauer);

		final Transition manuellePruefung = new Transition("Manuelle Prüfung", start, pruefen);
		manuellePruefung.setType(TransistionType.SYSTEM);
		script = """
				import groovy.json.JsonSlurper
				def jsonSlurper = new JsonSlurper()
				def map = jsonSlurper.parseText(data)
				map.dauer == 60;
				""";

		final Rule ruleMaxDauer = RuleCreator.build("Maximale Dauer", script);
		manuellePruefung.setRule(ruleMaxDauer);

		final Transition manuelleGenehmigung = new Transition("Manuelle Prüfung", pruefen, genehmigt);
		final Transition manuelleAblehnung = new Transition("Manuelle Prüfung", pruefen, abgelehnt);

		result.addTransition(automatischeGenehmigung);
		result.addTransition(manuellePruefung);
		result.addTransition(manuelleGenehmigung);
		result.addTransition(manuelleAblehnung);

		return result;
	}

}
